feat: add simple parser for QF_BV fragment of SMT-LIB v2
hargoniX/Leanwuzla pull request #3
Opened 2024-10-27 23:10 UTC by abdoo8080

This PR adds a parser for the QF_BV fragment of SMT-LIB to `leanwuzla`. The parsing is done in 3 stages:
 - string to S-expressions
 - S-expressions to a malformed Lean expression
 - Malformed Lean expression to a proper Lean expression

The parser and DSL for S-expressions was written by Wojciech Nawrocki. The dependency on my fork of `Qq` is because https://github.com/leanprover/lean4/pull/5323 made a breaking change (fixed in https://github.com/leanprover-community/quote4/pull/62)

2024-10-28 13:51 UTC, hargoniX requested changes

2024-10-28 13:51 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +import Qq
Your Qq PR fixes something that should already be fixed on the nightly-testing branch. In general PRs against leanprover-community projects should probably not touch the master toolchain as that is more or less implicitly guaranteed to be the latest stable release.

Beyond that all of the terms in this file seem to be trivially constructible with `mkApp`, `mkConst` and `mkAppM` unless I'm overlooking something? I would like to avoid depending on `Qq` if possible as it poses exactly the potential issue of being unable to update to a nightly if it is not yet fixed and we want to evaluate something in the future.

For things like
```
let α := (← parseTerm x).fst
if α == q(Bool) then
```
You can use `let_expr` or `match_expr`.

2024-10-28 13:51 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +  parseVar? (s : Sexp) : ParserM (Option (Expr × Expr)) := do
You can use `let .atom n := s | return none` here to get much more readable code.

2024-10-28 13:51 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +      return (q(BitVec $w), q($x / $y))
This translation is unsound, Lean's `udiv`, `urem` etc. has a different behavior upon diving by `0` compared to SMT. You need to translate to `smtUdiv` (we also need to add support for `smtUdiv` to LeanSAT but that's trivial, I'll do it today).

2024-10-28 13:51 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +      return (q(BitVec $w), q($x % $y))
Not quite sure about the remainder behavior matching up or not, probably worth to check.

2024-10-28 13:51 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +    parseTerm p >>= pure ∘ Prod.snd
It would be nice if you could use `do` notation instead of combinators etc. There is lots of people working on Lean that are not (and do not plan to be) familiar with the combinator style of monadic programming so this would make the code more accessible to them.

If you want to stick with the combinators: Most of the binds here are `<$>` in disguise aren't they?

2024-10-28 13:51 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +  bvars : Std.HashMap Name (Expr × Nat) := {}
Do we really need to work with `bvars` manually here? I'm feel like the code would be much simpler to understand if we were to use free variables and a persistent hash map to track them? Or is this performance critical in order to get things to fly on large SMT input files?

2024-10-28 15:06 UTC, abdoo8080 commented on Leanwuzla/Parser.lean
> +      return (q(BitVec $w), q($x % $y))
Thanks for pointing this out: Lean and SMT-LIB agree in this case (return the numerator). Here is the semantics copied from SMT-LBI (`[[_]] : [0, m) → {0, 1}`):

```
   [[(bvudiv s t)]] := if bv2nat([[t]]) = 0
                       then λx:[0, m). 1
                       else nat2bv[m](bv2nat([[s]]) div bv2nat([[t]]))

   [[(bvurem s t)]] := if bv2nat([[t]]) = 0
                       then [[s]]
                       else nat2bv[m](bv2nat([[s]]) rem bv2nat([[t]]))
```

2024-11-02 07:43 UTC, abdoo8080 commented on Leanwuzla/Parser.lean
> +      return (q(BitVec $w), q($x / $y))
Thanks for pointing this out! It would have taken me a long time to debug!

2024-11-02 07:45 UTC, abdoo8080 commented on Leanwuzla/Parser.lean
> +    parseTerm p >>= pure ∘ Prod.snd
`do` notation is good enough. Sometimes, I get tempted to use point-free coding style.

2024-11-02 07:54 UTC, abdoo8080 commented
> Oh, I just noticed my comment on Qq didn't go through:
> 
> First things first the change you are fixing in your Qq PR is already done on the nightly-testing branch. In general PRs to master of well supported leanprover-community projects such as Qq shouldn't change the lean-toolchain as its supposed to be the latest stable release. The FRO takes care of providing a nightly-testing branch that stays compatible with the latest nightly and merges it in when we do a new release.

Thanks for the clarification!

> Furthermore all of the Qq uses here seem pretty trivially replacable with `mkApp`, `mkAppM` and `mkConst` here? Qq has its place when we are doing really funky reflections between the meta level and the system but in this situation I think it's mostly over kill. If we avoid the dependency we can also just always blindly updated to the latest nightly to evaluate it without having to wait for potential fixes on Qq.

I've removed all uses of Qq. The SMT2 parser isn't a monad on top of `MetaM`, so I can't use `Meta.mkAppM` (though I could make it so). That's why I initially wanted to use Qq.

2024-11-02 08:11 UTC, abdoo8080 commented on Leanwuzla/Parser.lean
> +  bvars : Std.HashMap Name (Expr × Nat) := {}
While performance is a concern, my primary goal was to avoid stack-overflows from using Lean's metaprogramming framework (`CoreM` and `MetaM`). I haven't considered implementing the locally nameless approach myself. Let me see if I can come up with a reasonably efficient version of that.

2024-11-02 10:50 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +  bvars : Std.HashMap Name (Expr × Nat) := {}
Why would you be getting stack overflows from `CoreM` and `MetaM` but not from your own implementations? If you are experiencing something like that I would consider that a bug that needs to be fixed in `CoreM` or `MetaM` functions, there is no reason that a hand rolled version should be able to get rid of a stack overflow that I can think of.

2024-11-02 15:27 UTC, abdoo8080 commented on Leanwuzla/Parser.lean
> +  bvars : Std.HashMap Name (Expr × Nat) := {}
I encountered stack-overflows when dealing with variables using `Meta.withLocalDecls` (which isn't tail-recursive) and `Meta.withLocalDecl`/`Meta.withLetDecl` (with continuations forcing my code to not be tail-recursive). I considered directly working with `LocalContext`, but its API has "Do not use directly" warnings. Since updating the `LocalContext` isn't going to buy me much, I decided to implement my own context. However, if using it will make the code easier to understand, I'm more than happy to switch.

By the way, I don't think these stack-overflow issues are bugs in the `MetaM` functions. They were designed to handle many corner cases that don't typically occur in SMT-LIB's very large but simple expressions.

2024-11-02 23:37 UTC, hargoniX commented on Leanwuzla/Parser.lean
> +  bvars : Std.HashMap Name (Expr × Nat) := {}
You are referring to the parallel `let` binder code I assume? I guess if the binders are truly that large we can keep the code here for now. I'll check with other FRO people whether we might want to have an API that supports such a use case.

2024-11-03 12:02 UTC, hargoniX commented on Leanwuzla/Aux.lean
> +@[bv_normalize] theorem BitVec.sshiftRight'_eq (x : BitVec w) (n : BitVec v) : x.sshiftRight' n = x.sshiftRight n.toNat :=
This is not a good rewrite. LeanSAT doesn't reason about natural numbers like this, only the double BitVec version.

2024-11-03 18:11 UTC, abdoo8080 commented on Leanwuzla/Aux.lean
> +@[bv_normalize] theorem BitVec.sshiftRight'_eq (x : BitVec w) (n : BitVec v) : x.sshiftRight' n = x.sshiftRight n.toNat :=
Well... it looks like the tactic only supports `sshiftRight` 😅

```lean
/-
The prover found a potentially spurious counterexample:
- It abstracted the following unsupported expressions as opaque variables: [(2#4).sshiftRight' 1#4]
Consider the following assignment:
(2#4).sshiftRight' 1#4 = 0xf#4
-/
example : (2#4).sshiftRight' 1#4 = 1#4 := by
  bv_decide
```

2024-11-03 20:46 UTC, abdoo8080 commented on Leanwuzla/Parser.lean
> +  bvars : Std.HashMap Name (Expr × Nat) := {}
I haven't encountered large parallel lets, but I have seen large nested ones (500K+). By the way, I discovered that the cache was very harmful in these cases. So, I removed it and simplified the parser to directly compute the de Bruijn index.

2024-11-03 22:07 UTC, hargoniX commented on Leanwuzla/Aux.lean
> +@[bv_normalize] theorem BitVec.sshiftRight'_eq (x : BitVec w) (n : BitVec v) : x.sshiftRight' n = x.sshiftRight n.toNat :=
Ah I guess I forgot to add support for symbolic signed shifts, this is certainly the case for all other shift operators.

2024-11-06 01:56 UTC, abdoo8080 commented on Leanwuzla/Sexp/Basic.lean
> +/-- Tokenize `s` with the s-expression grammar. Supported token kinds are more or less as in
I just finished refactoring the code to use Parsec. However, I observed a significant performance degradation after the switch. The largest benchmark, which is 1.9GB in size, now takes over 10 minutes to process, compared to less than 2 minutes previously (this is not important since the rest of the system struggles with it anyway). The symbols in this benchmark are quite long, and despite my effort to minimize memory reallocations, the slowdown remains considerable.

2024-11-06 08:42 UTC, hargoniX approved these changes
Thanks!

2024-11-06 08:42 UTC, merged